public enum AN_LicenseRequestResult
{
	RESULT_LICENSED = 0,
	RESULT_RETRY = 1,
	RESULT_NOT_LICENSED = 2,
	ERROR_CHECK_IN_PROGRESS = 3,
	ERROR_INVALID_PACKAGE_NAME = 4,
	ERROR_INVALID_PUBLIC_KEY = 5,
	ERROR_MISSING_PERMISSION = 6,
	ERROR_NON_MATCHING_UID = 7,
	ERROR_NOT_MARKET_MANAGED = 8,
	ERROR_UNKNOWN = 9
}
